axelarnetwork/axelar-docs

- pages/dev/design.md
- pages/dev/design/contracts.md
- pages/dev/design/meta.json
- pages/dev/meta.json
> chore: remove /design

- pages/dev/get-started.md
- Use `testnet` as the hello-world example for now until we properly replicate this pattern in other examples.  (Current PR https://github.com/axelarnetwork/axelar-local-gmp-examples/pull/10 )
- Emphasize RPC endpoints, contract addresses for local v testnet.  These are the only things you should need to change in order to switch between local and live deployment
> docs: iterate on "get started"

- pages/controller/add-evm-chain.md
- pages/learn/cli/axl-from-evm.md
- pages/learn/cli/axl-to-evm.md
- pages/learn/cli/ust-from-evm.md
- pages/learn/cli/ust-to-evm.md
- pages/node/basic.md
- pages/node/join-genesis.md
- pages/node/join.md
- pages/validator/external-chains/overview.md
- pages/validator/setup/backup.md
- pages/validator/setup/health-check.md
- pages/validator/setup/manual.md
- pages/validator/setup/register-broadcaster.md
- pages/validator/setup/stake-axl.md
- pages/validator/setup/vald-tofnd.md
- public/md/testnet-2/upgrade-path.md
- We should refactor docs code so that tabs set only a variable for things like a path `~/.axelar_testnet-2` or chain-id `axelar-testnet-casablanca-1` so that we don't duplicate every CLI command x times for x networks.
- Some broken docs code removed in https://github.com/axelarnetwork/axelar-docs/commit/016f818fdf5a818406cf0afb4855de8ffe371db9 .  That page needs to be reworked anyway so not worth the time to figure out how to fix it.
> chore: testnet-2 tabs

- pages/validator/setup/register-broadcaster.md
If you're not on mainnet, this command will fail with failure to find keys for validator, since it is looking in .axelard
> Add param for --home 

- pages/controller.md
- pages/dev/gas-receiver.md
- pages/resources/mainnet.md
- pages/resources/testnet-2.md
- pages/resources/testnet.md
Request:
> Rename "fees" to "relayer gas fees" and make it clear that these fees are to cover gas costs across chains.
I think this is mostly already done, so there's not much to do in this PR.  The only non-trivial change is in "resources" section.
> fix: fees wording

- data/cosmos_chains.json
- data/ibc_channels.json
Opened channels between `axelar-testnet-lisbon-3` and `uni-3`
```
Success: Channel {
ordering: Unordered,
a_side: ChannelSide {
chain: BaseChainHandle {
chain_id: ChainId {
id: "uni-3",
version: 3,
},
runtime_sender: Sender { .. },
},
client_id: ClientId(
"07-tendermint-11",
),
connection_id: ConnectionId(
"connection-4",
),
port_id: PortId(
"transfer",
),
channel_id: Some(
ChannelId(
"channel-4",
),
),
version: None,
},
b_side: ChannelSide {
chain: BaseChainHandle {
chain_id: ChainId {
id: "axelar-testnet-lisbon-3",
version: 3,
},
runtime_sender: Sender { .. },
},
client_id: ClientId(
"07-tendermint-45",
),
connection_id: ConnectionId(
"connection-16",
),
port_id: PortId(
"transfer",
),
channel_id: Some(
ChannelId(
"channel-16",
),
),
version: None,
},
connection_delay: 0ns,
}
```
> Adding uni-3 Juno Testnet to axelar-testnet-lisbon-3

- pages/dev/gmp/executor-service.md
- pages/dev/gmp/gmp-tracker-recovery/error-debugging.md
- pages/dev/gmp/gmp-tracker-recovery/meta.json
- pages/dev/gmp/gmp-tracker-recovery/monitoring.md
edit some existing detail about the Error Execution Message and move them to a new separate page (in the GMP's `monitoring-recovery` section)
> feat: add a new Error Execution Message page

- pages/node/config-node.md
The $HOME variable is exportable and can be used independent of a specific shell.
> feat: improve node config page

- pages/dev/axelarjs-sdk/tx-status-query-recovery.md
Noticed that the interface displayed here...
https://docs.axelar.dev/dev/axelarjs-sdk/tx-status-query-recovery#query-transaction-status-by-txhash
...was different from the actual result. I've made a small edit to the documentation page to reflect the difference.
> Updated queryTransactionStatus documentation

- pages/node/basic.md
- https://github.com/axelarnetwork/axelar-docs/compare/feat/basic-node-mgmt?expand=1#diff-6f7f43619d794516f84121153f5aab9894480ae1c25c9d1760e02876f64adf4aR19
I added "&" at the end of the command to have the command running in the background, if we don't add it we are stuck until we kill the process.  We also can add [nohup](https://linuxhint.com/how_to_use_nohup_linux/) command at the beginning of the line but it seems it does not work well on Mac.
- Regarding the "axelard status" command, the output is not user friendly. We can use a command like : 
curl -s localhost:26657/status | jq '.result.sync_info' | grep '"catching_up": true' > /dev/null 2>&1 && echo "Node is catching up" || echo "Node is not catching up"
It will directly print the result to the user (we should add curl and jq as …
> feat: improve node mgmt

- pages/dev/general-message-passing/gmp-messages.mdx
- pages/dev/general-message-passing/gmp-tokens-with-messages.mdx
- pages/dev/reference/mainnet-chain-names.mdx
- pages/dev/reference/testnet-chain-names.mdx
If developers implement the interface directly, they'll need to manually verify the contract call, which is not recommended. Instead, developers should be extending `AxelarExecutable`, and only implementing the relevant `_execute` method.
CC: @vladwulf per our conversation today
> fix: change references to IAxelarExecutable to recommend AxelarExecutable instead

- pages/dev/general-message-passing/gas-services/pay-gas.mdx
> fix: add correct path to broken link in pay-gas page

- public/samples/interchain-token-simple.sol
It seems that no one is using the tokens owned by the contract, so removed as irrelevant from this sample.
> feat: simplify erc20 example

- pages/resources/governance/community-pool-proposals.mdx
`--chain-id axelar-dojo-1` needs to be explicitly specified if `AXELARD_CHAIN_ID` not set, other wise following error will happen  
```
{"height":"0","txhash":"997782FA19F3158D66632111F0287621B9ED1667F2CAEE78BBCC3335D6991F2B","codespace":"sdk","code":4,"data":"","raw_log":"signature verification failed; please verify account number (284247) and chain-id (axelar-doj
o-1):unauthorized","logs":[],"info":"","gas_wanted":"257751","gas_used":"54670","tx":null,"timestamp":"","events":[]}
```
> chore: update gov proposal community-pool-spend cli

- src/pages/learn/txduration.mdx
minor inaccuracy in our table for finality on time for cometbft. It says 1-3 seconds when it is in fact instant
> CometBFT Time Change

- src/pages/dev/send-tokens/interchain-tokens.mdx
Hello.
Merging this PR will fix a broken link that is supposed to link to the pages of the deployed smart contracts
> fix: Update link that redirect to deployed contracts

- src/pages/resources/mainnet.mdx
The heading for Assets has changed breaking existing links to it.
> fix: revert assets heading

- src/pages/dev/general-message-passing/gas-services/pay-gas.mdx
- src/pages/dev/general-message-passing/gas-services/refund.mdx
Was pointed out that we do not support payGasForContractCall we only support native gas payment. Commented out all references for now just in case we want to add this back in the docs later
> Remove reference to PayGasForContractCall

- src/data/evm_assets.json
- src/pages/resources/testnet.mdx
Renamed sepolia to `ethereum-sepolia` to fix bug on assets not appearing on testnet docs. 
Also added helper text to learn more on wrapped assets to match what we already have for mainnet assets
> Bugfix for testnet assets

- src/data/evm_chains.json
Re-ranked both mainnet and testnet chains according to the tier list on [Axelarscan](https://axelarscan.io/)
Order:
* Polygon
* Osmosis
* BNB Chain
* Avalanche
* Arbitrum
* Ethereum
* Fantom
* Moonbeam
* Terra (Classic)
* Celo
* Terra
* Kujira
* Optimism
* Base
* Kava
* Linea
* Mantle
* Scroll
* Filecoin
* Centrifuge
* Immutable
> fix: reorder chains according to Axelarscan popularity

- src/pages/dev/send-tokens/interchain-tokens/create-token.mdx
- src/pages/dev/send-tokens/interchain-tokens/upgrade-tokens.mdx
- Add hyperlinks to ITS and Factory addresses on Blockscan
- Add what next after deploying the interchain token, which is to do an interchain transfer
- Add a step to approve ITS after deploying canonical token before doing ITS transfer
- Remove the tokenID retrieval step where it's not required
- Add steps to give permission to ITS on all chains before doing interchain transfer for pre-existing token
> fix: update steps to create custom interchain token

- src/data/evm_assets.json
fix for prod issue of assets not appearing in docs
NOTE: chain name is ethereum-sepolia, not sepolia.
Fix: #698
> fix: evm assets not appearing in docs

- src/pages/resources/testnet/upgrades/v35.mdx
Bump release to the new patch version
> chore: bump release version to v0.35.4

- src/pages/dev/reference/testnet-contract-addresses.mdx
- src/pages/resources/testnet/upgrades/v17.mdx
- src/pages/resources/testnet/upgrades/v18.mdx
- src/pages/resources/testnet/upgrades/v19.mdx
- src/pages/resources/testnet/upgrades/v20.mdx
- src/pages/resources/testnet/upgrades/v21.mdx
- src/pages/resources/testnet/upgrades/v22.mdx
- src/pages/resources/testnet/upgrades/v23.mdx
- src/pages/resources/testnet/upgrades/v24.mdx
- src/pages/resources/testnet/upgrades/v25.mdx
- src/pages/resources/testnet/upgrades/v26.mdx
- src/pages/resources/testnet/upgrades/v27.mdx
- src/pages/resources/testnet/upgrades/v28.mdx
- src/pages/resources/testnet/upgrades/v29.mdx
- src/pages/resources/testnet/upgrades/v31.mdx
- src/pages/resources/testnet/upgrades/v32.mdx
- src/pages/resources/testnet/upgrades/v33.mdx
- src/pages/resources/testnet/upgrades/v34.mdx
Testnet-2 was removed a while ago, rename testnet-1 to testnet to reduce confusion
> refactor: rename testnet-1 to testnet

- src/pages/dev/axelarjs-sdk/axelar-query-api.mdx
[AXE-3184](https://axelarnetwork.atlassian.net/browse/AXE-3184)
This PR updates the `estimateGasFee` usage to the latest version of `axelarjs-sdk` (v0.14.1).
[AXE-3184]: https://axelarnetwork.atlassian.net/browse/AXE-3184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update `estimateGasFee` doc

- src/layouts/navigation.ts
- src/pages/dev/general-message-passing/express.mdx
- Added info about Express transaction liquidity being equivalent to the value of the transaction itself
- Re-organized and reworded some content for clarity
- Moved the doc to be last in the GMP section, for differentiation purposes
Preview: https://axelar-docs-git-marty-express-gmp-capital-axelar-network.vercel.app/dev/general-message-passing/express
> fix: add info to Express docs

- src/layouts/navigation.ts
- src/pages/validator/amplifier/verifier-onboarding.mdx
Originally from PR #729 by @StephenFluin.
- Renamed "Validator" / "Worker" to "Verifier" per instructions from Liana
- Created new **Amplifier** folder / section, added file as **Become a Verifier** to left nav
Preview: https://axelar-docs-git-marty-amplifier-worker-on-fb67f2-axelar-network.vercel.app/validator/amplifier/verifier-onboarding
> feat: add beginning verifier docs

- src/layouts/navigation.ts
- src/pages/dev/general-message-passing/overview.mdx
- src/pages/dev/general-message-passing/verify-gmp-tx.mdx
1. Added docs for evm + cosmos gmp tx verification
2. Added warning for sending txs sent to axelar chain (which we do not yet support)
@milapsheth if you have time feel free to review the cosmos gmp verification to ensure it's accurate. Thanks
> feat: Inbound Transaction Verification

- src/components/evm/assets.jsx
- src/styles/main.scss
added wrapping to long denoms so that the entire table is not offset when going through all assets
As referenced here: https://github.com/axelarnetwork/axelar-docs/issues/817
> [bugfix]: All Assets table

- src/pages/validator/amplifier/verifier-onboarding.mdx
Preview: https://axelar-docs-git-marty-amp-verifier-updates-axelar-network.vercel.app/validator/amplifier/verifier-onboarding
> fix: update verifier doc with ceremony notes

- src/components/evm/assets.jsx
Makes the asset loader still work and more resilient to malformations.
Fixes #890
> fix: assets not loading with invalid json

- src/layouts/navigation.ts
- src/pages/dev/amplifier/chain-integration/integrate-a-chain.mdx
- src/pages/dev/amplifier/chain-integration/introduction.mdx
- vercel.json
* Amplifier
* Introduction
* Integrate a chain
* GMP with Amplifier example
* Amplifier
* Introduction
* Chain Integration
* Introduction
* Integrate a chain
* GMP with Amplifier example
* Make current "Chain Integration" page into an "Intro" page, add appropriate redirect
* Make the tutorial into its own "Integrate a Chain" page
* Change `navigation.ts` to reflect new structure
* Add link to new "Integrate a Chain" page for all "tutorial" references in intro
> feat: new integrator section on amplifier docs

- src/pages/dev/amplifier/gmp-example.mdx
the fenced code block for the `construct_proof()` example call is missing the 'bash' identifier
the code block is not rendered the same as other examples on the page and the contained code is truncated on the page
adds 'bash' identifier to fix formatting
> fix: broken code formatting in "gmp-example" page

- src/pages/validator/troubleshoot/unjail.mdx
> fix: validator unjailing testnet chain id

- src/pages/dev/amplifier/chain-integration/integrate-a-chain.mdx
Update instantiation instructions for the multisig prover on chain integration doc to reflect [current fields on GitHub](https://github.com/axelarnetwork/axelar-amplifier/blob/ampd-v0.4.0/contracts/multisig-prover/src/msg.rs)
Preview: https://axelar-docs-git-marty-multisig-prover-ins-dd0df7-axelar-network.vercel.app/dev/amplifier/chain-integration/integrate-a-chain
> fix: update new multisig prover instantiation fields

- src/pages/validator/amplifier/verifier-onboarding.mdx
Addresses comments on #996 
Preview: https://axelar-docs-git-marty-verifier-binary-sup-718142-axelar-network.vercel.app/validator/amplifier/verifier-onboarding
> fix: tabbed verifier onboarding instructions

- src/pages/validator/amplifier/verifier-onboarding.mdx
* Change numbered steps for alias / symlink into different tabbed sections: either symlink, `bash` permanent alias, or `zsh` permanent alias
* Change `BINARY NAME` to `BINARY PATH`
* Add instructions for running `ampd —version` to verify installed version
* Add `chain_name="ethereum-sepolia”` to sample `config.toml`
* Replace home directory with Downloads folder in commands referring to the `ampd` path
* Remove non-happy-path instructions
Preview: https://axelar-docs-git-marty-fix-verifier-onboarding-axelar-network.vercel.app/validator/amplifier/verifier-onboarding
> fix: various verifier onboarding doc issues

- src/pages/validator/amplifier/verifier-onboarding.mdx
Preview: https://axelar-docs-git-marty-remove-caution-axelar-network.vercel.app/validator/amplifier/verifier-onboarding
> fix: remove empty caution from verifier onboarding doc

- src/pages/dev/amplifier/gmp-example.mdx
- Fix `source_address` and `destination_address` to match new [`devnet-amplifier` contract deployments](https://github.com/axelarnetwork/axelar-contract-deployments/pull/187/files)
- Update formatting for `wasm` commands
- Fix formatting (links and missing parenthesis)
Preview: https://axelar-docs-git-marty-gmp-example-contrac-dedd65-axelar-network.vercel.app/dev/amplifier/gmp-example
> fix: GMP example contract addresses

- src/pages/dev/amplifier/chain-integration/integrate-a-chain.mdx
- Add tabs
- Bump ampd version to 0.6.0
Preview: https://axelar-docs-git-marty-update-chain-int-tutorial-axelar-network.vercel.app/dev/amplifier/chain-integration/integrate-a-chain
> fix: update chain integration tutorial

- src/pages/dev/amplifier/chain-integration/integrate-a-chain.mdx
Update `domain_separator` param in multisig prover instantiation instructions for chain integration tutorial because it was [updated](https://github.com/axelarnetwork/axelar-amplifier/commit/16a40d817d93cdd7fc8301adfce59d51107d166c) from a hash into a hex string for better readability.
Preview: https://axelar-docs-git-marty-update-domain-separator-axelar-network.vercel.app/dev/amplifier/chain-integration/integrate-a-chain#instantiate-the-multisig-prover
> fix: update domain_separator

- src/layouts/navigation.ts
- src/pages/validator/amplifier/verifier-rotations.mdx
Preview: https://axelar-docs-git-marty-verifier-rotations-doc-axelar-network.vercel.app/validator/amplifier/verifier-rotations
> feat: verifier rotations doc

- src/pages/dev/amplifier/chain-integration/governance-proposals.mdx
The `store-instantiate` proposal for the Amplifier multisig prover cannot be submitted without a `gateway_address`, which the integrator can only get once their proposal to store and instantiate the gateway passes. Add a note in the non-EVM prover instantiation step to make this explicit.
Preview: https://axelar-docs-git-marty-prover-note-axelar-network.vercel.app/dev/amplifier/chain-integration/governance-proposals/#proposal-to-instantiate-the-prover-contract
> fix: add note about prover contract gov proposal

- src/content/docs/dev/amplifier/chain-integration/integrate-a-chain.mdx
Title: "Search the output of this command and note the _contract_address"
This item should be numbered as 3 on the interface, but it is currently being displayed as 1.
> fix: numbering issue under 'Instantiate the contract'

- public/samples/gmp-senderreceiver.sol
- src/content/docs/dev/general-message-passing/executable.mdx
- src/content/docs/dev/general-message-passing/gmp-messages.mdx
- src/content/docs/dev/general-message-passing/gmp-tokens-with-messages.mdx
various fixes of broken links and examples effected by `0.6` updated
> chore: update gmp doc breaking 0.6 changes

- src/content/docs/dev/general-message-passing/gmp-tokens-with-messages.mdx
['Send Messages with Tokens'](https://docs.axelar.dev/dev/general-message-passing/gmp-tokens-with-messages/#call-a-contract-on-chain-b-from-chain-a-and-attach-some-tokens) section tells `AxelarExecutable` is required, but this actually needs to be `AxelarExecutableWithToken` because we are sending a token with the message.
> fix: update contract name to AxelarExecutableWithToken

- src/components/footer/footer.astro
Reported on Telegram:
> "scroll down, bottom there is a discord icon
> redirects to a discord server (prob a scam server) that asks verification though a third party  third patry asks to send a tx in my case on eth network, whick tried to get all my cETH (compound eth = eth staked on compound protocol)"
> Fix Discord Link

- src/config/variables.ts
The [documentation](https://docs.axelar.dev/resources/contract-addresses/mainnet/) still shows `v1.0.5` as the latest version to use, and some node-operators have been having trouble with syncing up their nodes because of that.
> Update axelard mainnet to v1.1.3

- src/components/footer/footer.astro
- src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/link-custom-tokens-deployed-across-multiple-chains-into-interchain-tokens.mdx
- src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-canonical-token.mdx
- src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-token.mdx
Updated the Twitter URL from https://twitter.com to https://x.com to reflect the platform's rebranding.
> fix: update Twitter URL to x.com format

- src/content/docs/validator/external-chains/xrpl.mdx
- src/layouts/navigation.ts
Add instructions for setting up Ripple's XRPL `rippled` Testnet & Mainnet validator node.
These instructions are just about setting up the XRPL node. Regarding updating `ampd` to communicate with this node, I'd recommend adding something along these lines in the relevant location:
```md
Assuming you [have set up your Axelar Amplifier `ampd` verifier node](https://docs.axelar.dev/validator/amplifier/verifier-onboarding/),
append the following handlers to the end of your configuration file (usually `~/.ampd/config.toml`):
[[handlers]]
multisig_contract="axelar19jxy26z0qnnspa45y5nru0l5rmy9d637z5km2ndjxthfxf 5qaswst9290r"
multisig_prover_contract="axelar1ys83sedjffmqh70aksejmx3fy3q2d7twm3msurk 7wn3l6nkwxp0sfelzhl"
type="XRPLMultisigSigner"
[[handlers]]
chain_name="xrpl" …
```
> feat: add XRPL node setup guide

- src/content/docs/validator/external-chains/xrpl.mdx
* Include recommended hardware requirements instead of minimum.
* Update the `[ips]` stanza for the new rippled version`2.4.0`.
> fix: update XRPL node setup guide

- astro.config.mjs
- src/content/config.ts
- src/content/docs/resources/contract-addresses/mainnet.mdx
- src/content/docs/resources/contract-addresses/testnet.mdx
- src/content/docs/resources/rpc/resources.mdx
- src/pages/[...slug].astro
This PR adds support for manually setting meta descriptions and titles to improve SEO control. It also cleans up the sitemap by removing hidden or unused page links, ensuring only relevant pages are indexed.
follow up PR for SEO enhancements.
> feat: New logic to add Manual meta descriptions + title, remove hidden/unused page links from sitemap
