pages/dev.md

Only revised the examples GitHub links and added NFT linker to the examples section.

Update GitHub repo links of dev exampls.

---

pages/validator/external-chains/avalanche.md
pages/validator/external-chains/fantom.md
pages/validator/external-chains/moonbeam.md
pages/validator/external-chains/polygon.md

fix: update external chains instructions

---

pages/dev/get-started.md

As per discussion https://github.com/axelarnetwork/axelar-docs/pull/27#discussion_r863332960

fix: revert examples tweak

---

data/evm_chains.json
pages/learn/cli/axl-from-evm.md
pages/learn/cli/axl-to-evm.md
pages/learn/cli/ust-from-evm.md
pages/learn/cli/ust-to-evm.md
pages/node/basic.md
pages/node/config.md
pages/node/join-genesis.md
pages/node/join.md
pages/node/meta.json
pages/resources/meta.json
pages/resources/testnet-2.md
pages/validator/setup/backup.md
pages/validator/setup/health-check.md
pages/validator/setup/overview.md
pages/validator/setup/register-broadcaster.md
pages/validator/setup/stake-axl.md
public/md/testnet-2/upgrade-path.md

No content yet on new join scripts.  First I want to merge the new testnet-2 resources page so I can test new join scripts pull version number from testnet-2 resources page.
CLI config and tidy included just for fun.

docs: add testnet-2 resources, CLI config page, tidy some CLI commands

---

pages/validator/setup/manual.md
yarn.lock

I see people like manual instructions, usually I saw people setting their nodes up using this doc only, and someone made a [video](https://www.youtube.com/watch?v=wnzMrnE_o9k&ab_channel=CryptoSailors) too using these.
So I thought I should improve a things or two, when I first written these, I had hardcoded the versions, fixing that. This PR does:
1. Fixes hardcoded versions
2. Adds commands to recover keys
3. Adds Upgrade instructions: https://github.com/axelarnetwork/webdocs/issues/64

update instructions and add steps to upgrade

---

pages/validator/external-chains/avalanche.md
pages/validator/external-chains/ethereum.md
pages/validator/external-chains/fantom.md
pages/validator/external-chains/moonbeam.md
pages/validator/external-chains/polygon.md

- Updated guides for the external chains
- Fixed requirements/versions/etc. while keeping the same structure
- Added notes/instructions for Mainnet vs Testnet.

docs: update external chains guides

---

next.config.js
pages/node/basic.md
pages/node/join-genesis.md
pages/node/join.md
pages/node/meta.json
pages/validator/external-chains/overview.md
pages/validator/setup/backup.md
pages/validator/setup/config.md
pages/validator/setup/overview.md
pages/validator/setup/register-broadcaster.md
pages/validator/setup/stake-axl.md
pages/validator/setup/vald-tofnd.md

see commit history for details

fix: misc fixes

---

pages/validator/external-chains/moonbeam.md

Added flags for external access to the RPC ports.

docs: update moonbeam flags

---

data/ibc_assets.json
pages/dev/gmp-tracker.md

-  add more detail about manual GMP execution via axelarscan
-  update fee config

fix: update manual GMP execution and update fee config

---

pages/validator/setup/manual.md

fix: tabs rendering for complex CLI commands

---

pages/resources/wrapped-tokens.md

the same instructions work for Avalanche, Ethereum, Fantom, Moonbeam, Polygon.

doc: generalize wrapped token instructions

---

pages/validator/external-chains/ethereum.md

Add steps for  consensus Layer post Merge

Add steps for  consensus Layer post Merge

---

pages/resources.md

Add RPC, gRPC, LCD endpoints, mainnet, testnet-1

Add RPC endpoints

---

pages/resources/testnet.md

Merge once the testnet is upgraded

docs: update latest testnet version

---

pages/dev/build/chain-names/testnet.md

chore: update chain names

---

pages/resources/mainnet.md
pages/validator/setup/manual.md

Update latest version once network is upgraded

chore: update mainnet latest version

---

next.config.js
package.json

Added security headers to prevent clickjacking

chore: add secure headers

---

pages/resources/mainnet.md
pages/resources/testnet.md

add EVM addresses back to Resource

add EVM addresses back to Resource

---

components/web3/index.js
package.json
yarn.lock

check and show a message on the MM button if the user's wallet is already at the clicked chain.

show a message on the MM button if the user's wallet is already at the clicked chain.

---

pages/dev/axelarjs-sdk/tx-status-query-recovery.md
pages/dev/build/chain-names.md
pages/dev/build/chain-names/mainnet.md
pages/dev/build/chain-names/testnet.md
pages/node/join.md
pages/resources/metamask.md
pages/resources/wrapped-tokens.md
pages/validator/external-chains/ethereum.md
pages/validator/external-chains/overview.md

- Updated references to Goerli
- Update Eth node sync instructions
- Update chain names

fix: update goerli rpc instructions

---

pages/dev/guides/example-usdc.md
pages/dev/guides/meta.json

Porting this tutorial written by Euro and Galen over from Notion

feat: add circle USDC tutorial

---

components/evm/assets.js
components/evm/chains.js
components/ibc/channels.js

add the network chain names and asset ids to the Resources page

chore: add the network chain names, asset ids to the Resources page

---

pages/validator/external-chains/overview.md
pages/validator/setup/register-broadcaster.md

Added missing EVM links and snippets.

Update overview, register-broadcaster

---

pages/index.md

feat: improve welcome text on docs home

---

pages/validator/setup/manual.md

Ref: https://discord.com/channels/770814806105128977/935639401583771738/1045774055443271723

change restart to always

---

pages/dev/axelarjs-sdk/token-transfer-dep-addr.md

- Improve deposit address docs structure by adding transfer fees step
- Update code samples with working code + self contained examples
- Promote use of constants like `Environment` and `CHAINS`

chore: refactor docs

---

pages/dev/general-message-passing/recovery.mdx

fix: correct broken debugging link on recovery

---

components/dropdown.js

fix: dropdown color in dark mode

---

pages/dev/general-message-passing/gmp-messages.mdx

- Old link: [https://github.com/axelarnetwork/axelar-gmp-sdk-solidity/blob/main/contracts/executables/AxelarExecutable.sol](https://github.com/axelarnetwork/axelar-gmp-sdk-solidity/blob/main/contracts/executables/AxelarExecutable.sol)
- New link: [https://github.com/axelarnetwork/axelar-gmp-sdk-solidity/blob/main/contracts/executable/AxelarExecutable.sol](https://github.com/axelarnetwork/axelar-gmp-sdk-solidity/blob/main/contracts/executable/AxelarExecutable.sol)

fixed broken link

---

theme.config.jsx

Fixes: #396 
Preview works as expected, see screenshot below

fix: seo meta tags for docs to preview thumbnail on all social

---

pages/dev/general-message-passing/gas-services/pay-gas.mdx

fix: remove payGasForContractcall with aUSDC

---

pages/dev/general-message-passing/overview.mdx

fix: add correct path for supported evm chains

---

pages/dev/general-message-passing/gas-services/refund.mdx

fix: monitoring state GMP transaction broken link

---

components/markdown.js
pages/_app.mdx
styles/components/markdown.css

fix: add style to markdown table

---

pages/dev/general-message-passing/cosmos-gmp.mdx

fix: sample cosmos gmp middleware link

---

data/evm_assets.json
data/ibc_assets.json
data/tokens.json

feat: add axlETH/axlWBTC to other chains

---

pages/dev/send-tokens/interchain-tokens.mdx
public/samples/interchain-token-custom.sol
public/samples/interchain-token-iinterchaintoken.sol
public/samples/its-new-standard.sol

Built on top of the new Interchain Token Service: https://github.com/axelarnetwork/interchain-token-service/tree/main

feat: new interchain token documentation

---

src/pages/dev/reference/mainnet-contract-addresses.mdx
src/pages/dev/reference/testnet-contract-addresses.mdx

Fixed chains and assets filter button cannot be clicked https://docs.axelar.dev/dev/reference/testnet-contract-addresses

chore: fix filter button

---

src/pages/validator/external-chains/binance.mdx

- update binance finality check to use finalized tag

chore: update binance finality requirement

---

src/pages/dev/general-message-passing/example-usdc-cctp.mdx
src/pages/dev/general-message-passing/solidity-utilities.mdx

Looks like the library was moved a few months ago.

fix: paths and name of AddressString

---

src/layouts/Navigation.astro

add mantle blockchain to index

---

src/pages/resources/mainnet.mdx
src/pages/validator/setup/manual.mdx

Can merge this in after mainnet upgrade are complete

chore: update mainnet version doc

---

src/components/keplr/index.jsx
src/styles/main.scss

fix: keplr button color

---

src/styles/dark.scss

fix: improve dark style

---

src/data/resources.json

Update ws endpoint :
```
wscat -n -c ws://rpc-axelar.imperator.co/wss/websocket
Connected (press CTRL+C to quit)
> 
```

feat: update ws endpoint

---

src/pages/dev/send-tokens/overview.mdx

As indicated here: https://github.com/axelarnetwork/axelarjs-sdk/blob/c763d1cc0f3f01e298887e74bfaced2a4e2bd92f/src/libs/AxelarAssetTransfer.ts#L86

fix: add required properties `evmOptions` and `cosmosOptions`

---

src/pages/validator/external-chains/scroll.mdx

removed duplicated datadir and http settings from the service file of the Scroll EVM setup

Removed duplicated Scroll init parameters

---

src/pages/dev/reference/mainnet-contract-addresses.mdx
src/pages/dev/reference/testnet-contract-addresses.mdx

fix: copy and metamask client-side js in /dev

---

STYLE-GUIDE.md
src/pages/controller/add-evm-chain.mdx
src/pages/dev/axelarjs-sdk/tx-status-query-recovery.mdx
src/pages/learn/cli/axl-from-evm.mdx
src/pages/learn/cli/axl-to-evm.mdx
src/pages/learn/cli/ust-from-evm.mdx
src/pages/learn/cli/ust-to-evm.mdx
src/pages/resources/metamask.mdx
src/pages/resources/wrapped-tokens.mdx
src/pages/validator/external-chains/hero.mdx

fix: capitalization of MetaMask

---

src/layouts/navigation.ts
src/pages/dev/reference/interchain-token-service-rate-limit.mdx

- Added comprehensive documentation on the FlowLimit contract in the Interchain Token Service, detailing its role in regulating interchain token flows and ensuring stability and security.
- Covered key features like flow limit management, dynamic slot allocation, and provided Solidity code examples, along with guidance on setting and managing flow limits in various scenarios.

feat: add ITS rate limit guide

---

src/pages/validator/external-chains/immutable.mdx

Breakdown docker command to help operators adjust it to their environment

Breakdown docker command

---

src/components/chainlist.jsx

Fixes issue https://github.com/axelarnetwork/axelar-docs/issues/350

Expanded chainlist into a table

---

src/data/resources.json

feat: add implicit port to RPC endpoints

---

STYLE-GUIDE.md

Add conventions for Mint/Burn, Lock/Unlock, `TokenManager`

fix: update STYLE-GUIDE.md

---

public/samples/interchain-token-iinterchaintoken.sol

https://github.com/axelarnetwork/axelar-gmp-sdk-solidity/blob/main/contracts/libs/AddressBytes.sol

fix: update `AddressBytes` path

---

src/pages/dev/general-message-passing/gmp-messages.mdx
src/pages/dev/general-message-passing/gmp-tokens-with-messages.mdx
src/pages/dev/general-message-passing/overview.mdx
src/pages/dev/send-tokens/interchain-tokens/create-token.mdx
src/pages/dev/send-tokens/interchain-tokens/upgrade-tokens.mdx

Staged:
* https://axelar-docs-git-marty-chain-trust-axelar-network.vercel.app/dev/send-tokens/interchain-tokens/create-token
* https://axelar-docs-git-marty-chain-trust-axelar-network.vercel.app/dev/send-tokens/interchain-tokens/upgrade-tokens

fix: add interchain trust notice

---

astro.config.mjs
src/styles/dark.scss
src/styles/main.scss

fix: anchor links show up on hover

---

src/pages/resources/testnet/upgrades/v35.mdx

Update v0.35 testnet upgrade doc with more info

docs: update v0.35 testnet upgrade docs

---

src/layouts/navigation.ts
src/pages/dev/send-tokens/interchain-tokens/interchain-token-executable.mdx

feat: add ITS executable doc

---

src/pages/dev/intro.mdx

Preview: https://axelar-docs-git-marty-axelar-for-developers-axelar-network.vercel.app/dev/intro

fix: "Axelar for Developers" rewrite

---

src/layouts/navigation.ts
src/pages/dev/general-message-passing/express.mdx

feat: express docs

---

src/pages/dev/general-message-passing/express.mdx

quick update to the form users submit when express onboarding

fix: update express signup form

---

src/components/starlight/table-of-contents.astro
src/layouts/Section.astro
src/layouts/TableOfContents.astro
src/layouts/TableOfContentsHeading.astro
src/pages/dev/general-message-passing/overview.mdx
src/pages/dev/intro.mdx
src/pages/index.astro
src/scripts/active.ts
src/styles/dark.scss
src/styles/main.scss

Also standardized on in-content H1s away from pagetitles 
Fixed missing H2s on gmp overview
Fixes #737

feat: add table of contents

---

src/data/evm_chains.json
src/data/gas_services.json
src/data/gateways.json

https://axelarnetwork.atlassian.net/browse/AXE-3341
Add chain config, and addresses for Blast Mainnet

feat: add blast mainnet chain info

---

src/pages/dev/send-tokens/interchain-tokens/create-token.mdx
src/pages/dev/send-tokens/interchain-tokens/upgrade-tokens.mdx

fix: update code samples not to exceed 80 characters

---

vercel.json

Previews (with shortlinks):
- https://axelar-docs-git-marty-its-short-links-axelar-network.vercel.app/its/intro
- https://axelar-docs-git-marty-its-short-links-axelar-network.vercel.app/its/create-token
- https://axelar-docs-git-marty-its-short-links-axelar-network.vercel.app/its/upgrade-token
- https://axelar-docs-git-marty-its-short-links-axelar-network.vercel.app/its/token-executable
- https://axelar-docs-git-marty-its-short-links-axelar-network.vercel.app/its/rate-limit
- https://axelar-docs-git-marty-its-short-links-axelar-network.vercel.app/its/create-token-tutorial
- https://axelar-docs-git-marty-its-short-links-axelar-network.vercel.app/its/canonical-token-tutorial
- https://axelar-docs-git-marty-its-short-links-axelar-network.vercel.app/its/link-token-tutorial
They should all …

feat: add ITS shortlink redirects

---

src/data/evm_assets.json
src/data/tokens.json

https://axelarnetwork.atlassian.net/browse/AXE-3403

feat: update testnet configs

---

src/pages/dev/intro.mdx
src/pages/node/keyring.mdx

fix: typos in naming

---

src/pages/validator/external-chains/arbitrum.mdx

Update docs for arbitrum flags

---

vercel.json

fix: redirect to ITS glossary

---

src/pages/dev/amplifier/chain-integration.mdx

feat: add integration architecture and process

---

public/samples/on-chain-gas-estimate.sol
src/layouts/navigation.ts
src/pages/dev/gas-service/on-chain.mdx

Ready pending verification and testing with live on-chain contracts.

Add docs for on-chain gas estimation

---

src/pages/validator/amplifier/verifier-onboarding.mdx

Reverts axelarnetwork/axelar-docs#889
The new container specified here is not compatible.

Revert "fix: update Docker container"

---

src/layouts/navigation.ts
src/pages/resources/chain-onboarding.mdx
src/pages/resources/ibc-chain-onboarding.mdx

Add onboarding guide based on [Notion doc](https://www.notion.so/bright-ambert-2bd/Onboard-your-chain-d4e8b52abbb34a2b8a4923da9c2768c0?d=bce118df7b534a68b235c3c254ec97fe#fc3724468fcf4b22acb6338eb5c24ff9).
Preview: https://axelar-docs-git-marty-ibc-onboarding-axelar-network.vercel.app/resources/chain-onboarding

feat: add chain onboarding guide

---

src/pages/dev/amplifier/gmp-example.mdx

It would be useful to have a whole section or page somewhere on msg id formats (which formats are currently available, which to use, what to do if you need a different format, etc).

change msg id format in amplifier gmp example

---

src/data/evm_assets.json
src/data/evm_chains.json
src/data/gas_services.json
src/data/gateways.json
src/data/tokens.json

https://axelarnetwork.atlassian.net/browse/AXE-3908
https://axelarnetwork.atlassian.net/browse/AXE-3909

chore: update docs to include configs for polygon and linea sepolia

---

src/layouts/navigation.ts
src/pages/dev/general-message-passing/executable.mdx

added doc explaining axelar executable; what it is, how to implement, upgradeable caveat

feat: Axelar Executable Doc

---

src/layouts/navigation.ts
src/pages/dev/amplifier/add-rewards.mdx

Tells integrators how to check and add funds to a rewards pool.
Preview: https://axelar-docs-git-marty-adding-rewards-axelar-network.vercel.app/dev/amplifier/add-rewards
- [[Parrot] Amplifier Contract Learning Session](https://app.parrot.ai/page/9e94317d-165d-4b67-9dae-6e3424409106/f2e9f951-5839-5de2-98ee-71f17f4b449a)
- [[GitHub] Rewards contract doc on axelar-amplifier](https://github.com/axelarnetwork/axelar-amplifier/blob/6fd3612716fc6cf3b421ebe53939a71341731047/doc/src/contracts/rewards.md)
- [[GitHub] axelar-amplifier/contracts/rewards](https://github.com/axelarnetwork/axelar-amplifier/tree/6fd3612716fc6cf3b421ebe53939a71341731047/contracts/rewards)
- [[Notion] Amplifier Rewards Explained by ChatGPT](https://www.notion.so/bright-ambert-2bd/Amplifier-Rewards-Explained-by-ChatGPT-d2cf7 …

feat: add rewards (integrator) doc

---

src/pages/dev/send-tokens/interchain-tokens/intro.astro

fix: fixed broken its portal url

---

src/styles/dark.scss

Link and H1 were the same color in dark mode, making for a confusing user experience. Change H1 to white to prevent this.

fix: change dark mode H1s to white

---

src/pages/dev/amplifier/chain-integration/integrate-a-chain.mdx

Source of truth: https://github.com/axelarnetwork/axelar-contract-deployments/blob/main/axelar-chains-config/info/devnet-amplifier.json

feat: update codeIds based on 0.5.0 devnet update

---

src/pages/dev/general-message-passing/executable.mdx

Needed extra spaces to let markdown count the list items

fix: step ordering

---

src/pages/resources/community/community-pool-proposals.mdx

Preview: https://axelar-docs-kg34jokdp-axelar-network.vercel.app/resources/community/community-pool-proposals

fix: rewrite community proposal doc

---

src/pages/validator/amplifier/verifier-onboarding.mdx

Fixes https://github.com/axelarnetwork/support/issues/130

change ecsda -> ecdsa

---

src/pages/dev/amplifier/chain-integration/governance-proposals.mdx

Preview: https://axelar-docs-git-marty-escape-strings-axelar-network.vercel.app/dev/amplifier/chain-integration/governance-proposals

fix: CHAIN_NAME variable in integrator gov proposal docs

---

src/pages/validator/amplifier/verifier-onboarding.mdx

Will prevent breaks if we change the default in the future.

feat: explicitly specify chain finalization strategy

---

src/pages/validator/external-chains/immutable.mdx

update documentation to use latest tag on immutable geth images

chore: update immutable docker tag

---

src/pages/resources/static-configs/static-configs.mdx

https://www.npmjs.com/package/@axelarjs/api
only one @ in the library name

Typo Fix, Update static-configs.mdx

---

src/layouts/navigation.ts
src/pages/resources/testnet/upgrades/v1.0.mdx

Also flatten the navigation by removing extra single folder directories
[Preview link](https://axelar-docs-git-stephen-axelar-core-101-update-axelar-network.vercel.app/resources/testnet/upgrades/v1.0)

feat: add v1.0 upgrade instructions

---

src/pages/dev/amplifier/chain-integration/governance-proposals.mdx

- Add values where needed
- Remove repeat variables, under the assumption that devs will already have them stored because they're chaining the commands one after another.
Preview: https://axelar-docs-git-marty-update-variables-axelar-network.vercel.app/dev/amplifier/chain-integration/governance-proposals

fix: update chain integration gov doc with variables

---

src/pages/dev/amplifier/chain-integration/governance-proposals.mdx

Preview: https://axelar-docs-git-marty-integrator-name-axelar-network.vercel.app/dev/amplifier/chain-integration/governance-proposals

fix: give sample chain name on integrator doc

---

src/layouts/MainLayout.astro

feat: add canonical URLs

---

src/layouts/navigation.ts
src/pages/dev/amplifier/chain-integration/error-messages.mdx
src/pages/validator/amplifier/error-messages.mdx

Previews:
- Chain integrators: https://axelar-docs-git-marty-amplifier-error-messages-axelar-network.vercel.app/dev/amplifier/chain-integration/error-messages
- Verifiers / relayers: https://axelar-docs-git-marty-amplifier-error-messages-axelar-network.vercel.app/validator/amplifier/error-messages

feat: amplifier error messages doc

---

src/pages/validator/amplifier/governance-proposals.mdx

Preview: https://axelar-docs-git-marty-double-params-axelar-network.vercel.app/validator/amplifier/governance-proposals

fix: remove double params

---

src/pages/dev/amplifier/chain-integration/integrate-a-chain.mdx

Preview: https://axelar-docs-git-marty-update-integrator-tutorial-axelar-network.vercel.app/dev/amplifier/chain-integration/integrate-a-chain/

feat: update integration tutorial for mainnet v1.0

---

src/pages/dev/amplifier/chain-integration/integrate-a-chain.mdx

fix: remove invalid prover json

---

src/layouts/navigation.ts
src/pages/validator/amplifier/soroban.mdx

add soroban.mdx instructions

---

vercel.json

Redirect deleted pages to ITS intro

fix: ITS redirect

---

src/content/docs/resources/mainnet/upgrades/v21.mdx
src/content/docs/resources/mainnet/upgrades/v24.mdx
src/content/docs/resources/mainnet/upgrades/v26.mdx
src/content/docs/resources/mainnet/upgrades/v28.mdx
src/content/docs/resources/mainnet/upgrades/v29.mdx
src/content/docs/resources/mainnet/upgrades/v31.mdx

fix: number display order

---

src/content/docs/resources/mainnet/upgrades/v33.mdx

fix: numbering problem

---

src/content/docs/resources/mainnet/upgrades/v34.mdx

fix: numbering problem 'v34.mdx'

---

src/content/docs/dev/axelarjs-sdk/tx-status-query-recovery.mdx

Finishing up marty's pr for the gmp recover. will still want to develop this doc out further regarding available functionality for this section, but this fixes the existing issues we have there.

Chore/axelarjs sdk GMP recover fixes

---

src/data/evm_assets.json
src/data/ibc_assets.json
src/data/tokens.json

https://axelarnetwork.atlassian.net/browse/AXE-5296

feat: add config for assets requested by osmosis

---

src/content/docs/dev/amplifier/add-rewards.mdx
src/content/docs/dev/amplifier/chain-integration/governance-proposals.mdx

- minor touchups to reward pool doc
- added reward pool creation to governance section for amplifier

chore: reward pool touchups

---

src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/link-custom-tokens-deployed-across-multiple-chains-into-interchain-tokens.mdx
src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-canonical-token.mdx
src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-token.mdx

fix: unknown code block language "JavaScript" and add hardhat guide

---

src/layouts/navigation.ts

feat: add developer blog tutorials

---

src/content/docs/dev/amplifier/chain-integration/relay-messages/manual.mdx
src/content/docs/validator/amplifier/verifier-onboarding.mdx

1. manual gmp message example (devnet) 
2. fix for broken verifier command

chore: amplifier doc touchups

---

src/content/docs/validator/external-chains/sui.mdx

- Added some various fixes for the `sui` RPC node guide

add some small fixes for sui guide

---

src/content/docs/validator/external-chains/soroban.mdx

- Added some various fixes for the `soroban` RPC node guide

added some soroban guide fixes

---

astro.config.mjs
public/robots.txt
src/layouts/MainLayout.astro
vercel.json

This pr removes the logic of forces trailing slash URLs

remove: force trailing slash in url's

---

vercel.json

after removing the logic of forced trailing slash, the redirects in vercel.json were malfunctioning.
this pr solves that..

fix: redirects in vercel.json

---

astro.config.mjs
src/layouts/MainLayout.astro
src/scripts/index.ts
src/scripts/intercom.ts

This PR bloats the bundle by +1MB, look at peformance before merging.

add intercom

---

public/samples/interchain-token-custom.sol
src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/link-custom-tokens-deployed-across-multiple-chains-into-interchain-tokens.mdx
src/content/docs/dev/send-tokens/interchain-tokens/integrate-custom-token.mdx

fix: update instances of "erc20" to use standard "erc-20"

---

src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/link-custom-tokens-deployed-across-multiple-chains-into-interchain-tokens.mdx
src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-canonical-token.mdx
src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-token.mdx

fix: update interchain token developer guides to use sepolia

---

src/content/docs/dev/amplifier/introduction.mdx

Adding a mention of MDS to Amplifier intro page.

Add MDS mention to Amplifier introduction.mdx

---

src/content/docs/dev/send-tokens/interchain-tokens/create-new-interchain-token.mdx
src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-canonical-token.mdx
src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-token.mdx
src/content/docs/dev/send-tokens/interchain-tokens/integrate-custom-token.mdx
src/content/docs/dev/send-tokens/interchain-tokens/register-existing-token.mdx

feat: update interchain token service docs

---

src/content/docs/validator/external-chains/immutable.mdx
src/content/docs/validator/external-chains/xrpl-evm.mdx

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

src/content/docs/validator/external-chains/stellar.mdx
src/content/docs/validator/external-chains/xrpl-evm.mdx
src/content/docs/validator/external-chains/xrpl.mdx

new stellar testnet && xrpl/xrpl evm testnet

Chore/ampd configs 

---

src/content/docs/dev/send-tokens/interchain-tokens/developer-guides/link-custom-tokens-deployed-across-multiple-chains-into-interchain-tokens.mdx

fix: update interchain token factory reference

---

src/content/docs/validator/amplifier/verifier-onboarding.mdx

chore: tofnd setup note

---

src/content/docs/dev/send-tokens/interchain-tokens/no-code.mdx

https://axelarnetwork.atlassian.net/browse/AXE-9083

docs(tokens): update no-code setup documentation

---

src/content/docs/dev/general-message-passing/cosmos-gmp/cosmos-2way-manual-relay.mdx
vercel.json

https://axelarnetwork.atlassian.net/browse/AXE-9076

docs(cosmos-gmp): update manual relay guide for clarity

---

src/content/docs/dev/gas-service/intro.mdx
src/content/docs/dev/send-tokens/interchain-tokens/token-manager.mdx

https://axelarnetwork.atlassian.net/browse/AXE-9086
https://axelarnetwork.atlassian.net/browse/AXE-9079

docs(gas-service): update introduction and links in documentation

---

src/content/docs/dev/general-message-passing/gmp-tokens-with-messages.mdx

https://axelarnetwork.atlassian.net/browse/AXE-8943
https://axelarnetwork.atlassian.net/browse/AXE-8941

docs(gmp-tokens): improve clarity of message passing instructions

---

src/content/docs/validator/external-chains/solana.mdx
src/layouts/navigation.ts

Solana node setup documentation.

doc: Solana node setup added

---

src/content/docs/validator/external-chains/hedera.mdx

- Revisit `Hedera` documentation and update some outdated dependencies and instructions.

Revisit Hedera docs

---

src/content/docs/validator/external-chains/xrpl.mdx

* Update hardware requirements to 1.5TB.
* Configure node to store at least a month of ledger history (750k ledgers).
* Add `[server]` unauthorized access note.

fix: Update XRPL ledger history
